services:
  backend: 
    build:
      context: ../tennis
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
      - PYTHONUNBUFFERED=1
      # - IS_PROD=False 
    env_file:
      - .env.local
    volumes:
      - ../:/app
  celery:
    build:
      context: ../tennis
      dockerfile: Dockerfile
      target: dev
    command: /home/django/.local/bin/celery -A artoftennis worker -l info
    volumes:
      - ../:/app
    depends_on:
      - backend
      - redis
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=db_user
      - DATABASE_PASSWORD=db_password
      - DATABASE_NAME=tennis
      - DATABASE_PORT=5432
      - PYTHONUNBUFFERED=1
      # - IS_PROD=False 
    env_file:
      - .env.local
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - art_of_tennis_redis_data:/data
  db:
    image: postgres:alpine3.19
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - art_of_tennis_postgres:/var/lib/postgresql/data 
volumes:
  art_of_tennis_postgres:
  art_of_tennis_redis_data:
